In [1]:
import pandas as pd

df = pd.DataFrame({
    "Year": list(range(2015, 2020)),
    "Observation": [123, 39, 78, 52, 110],
})

In [2]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=5, step=1)
Index(['Year', 'Observation'], dtype='object')

In [3]:
df.dtypes

Year           int64
Observation    int64
dtype: object

In [4]:
year_df = df.set_index("Year")
year_df

      Observation
Year
2015          123
2016           39
2017           78
2018           52
2019          110

In [5]:
print(repr(pd.Timestamp("2020-01")))
print(repr(pd.Period("2020-01")))

Timestamp('2020-01-01 00:00:00')
Period('2020-01', 'M')

In [6]:
print(repr(pd.Timestamp("2020")))
print(repr(pd.Timestamp("2020-01-01 12:34")))
print(repr(pd.Period("2020-01-01")))
print(repr(pd.Period("2020-01-01", freq="M")))

Timestamp('2020-01-01 00:00:00')
Timestamp('2020-01-01 12:34:00')
Period('2020-01-01', 'D')
Period('2020-01', 'M')

In [7]:
ts_few = pd.to_datetime(["2020-01-01", "2020-01-02", "2020-01-03"])
ts_range = pd.date_range("2020-01-01", "2020-01-02", freq="8h")
print(ts_few)
print(ts_range)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 08:00:00',
               '2020-01-01 16:00:00', '2020-01-02 00:00:00'],
              dtype='datetime64[ns]', freq='8h')

In [8]:
print(ts_range.to_period())
print(ts_range.to_period(freq="D"))
print(ts_range.to_period(freq="W"))
print(ts_range.to_period().to_timestamp())

PeriodIndex(['2020-01-01 00:00', '2020-01-01 08:00', '2020-01-01 16:00',
             '2020-01-02 00:00'],
            dtype='period[8h]')
PeriodIndex(['2020-01-01', '2020-01-01', '2020-01-01', '2020-01-02'], dtype='period[D]')
PeriodIndex(['2019-12-30/2020-01-05', '2019-12-30/2020-01-05',
             '2019-12-30/2020-01-05', '2019-12-30/2020-01-05'],
            dtype='period[W-SUN]')
DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 08:00:00',
               '2020-01-01 16:00:00', '2020-01-02 00:00:00'],
              dtype='datetime64[ns]', freq='8h')

In [9]:
print(ts_few.strftime("%m/%d/%Y"))
print(ts_range.to_period().strftime("%Y %b ~ %H:%M"))

Index(['01/01/2020', '01/02/2020', '01/03/2020'], dtype='object')
Index(['2020 Jan ~ 00:00', '2020 Jan ~ 08:00', '2020 Jan ~ 16:00',
       '2020 Jan ~ 00:00'],
      dtype='object')

In [10]:
df = pd.DataFrame({"ts": ts_few})
df = df.assign(
    period=df["ts"].dt.to_period(),
    yr=df["ts"].dt.year,
    str=df["ts"].dt.strftime("%A, %B %-d"),
).set_index("ts")
df

                period    yr                  str
ts
2020-01-01  2020-01-01  2020  2020-01-01 00:00:00
2020-01-02  2020-01-02  2020  2020-01-02 00:00:00
2020-01-03  2020-01-03  2020  2020-01-03 00:00:00

In [11]:
olympic_running = pd.read_csv("../data/olympic_running_unparsed.csv")
olympic_running.head(10)

   Year  Length  Sex  Time
0  1896     100  men  12.0
1  1900     100  men  11.0
2  1904     100  men  11.0
3  1908     100  men  10.8
4  1912     100  men  10.8
5  1916     100  men   NaN
6  1920     100  men  10.8
7  1924     100  men  10.6
8  1928     100  men  10.8
9  1932     100  men  10.3

In [12]:
print(olympic_running["Sex"].unique())

['men' 'women']

In [13]:
print(olympic_running[["Sex", "Length"]].drop_duplicates())

       Sex  Length
0      men     100
31   women     100
54     men     200
84   women     200
102    men     400
133  women     400
147    men     800
178  women     800
201    men    1500
232  women    1500
244    men    5000
271  women    5000
277    men   10000
304  women   10000

In [14]:
pbs = (
    pd.read_csv("../data/PBS_unparsed.csv", parse_dates=["Month"])
    [["Month", "Concession", "Type", "ATC1", "ATC2", "Scripts", "Cost"]]
)
pbs

           Month    Concession         Type ATC1 ATC2  Scripts     Cost
0     1991-07-01  Concessional  Co-payments    A  A01    18228  67877.0
1     1991-08-01  Concessional  Co-payments    A  A01    15327  57011.0
2     1991-09-01  Concessional  Co-payments    A  A01    14775  55020.0
3     1991-10-01  Concessional  Co-payments    A  A01    15380  57222.0
4     1991-11-01  Concessional  Co-payments    A  A01    14371  52120.0
...          ...           ...          ...  ...  ...      ...      ...
67591 2008-02-01       General   Safety net    Z    Z      135   1591.0
67592 2008-03-01       General   Safety net    Z    Z       15    276.0
67593 2008-04-01       General   Safety net    Z    Z       11    165.0
67594 2008-05-01       General   Safety net    Z    Z       21    278.0
67595 2008-06-01       General   Safety net    Z    Z       57    491.0

[67596 rows x 7 columns]

In [15]:
a10 = pbs.loc[pbs["ATC2"] == "A10"]
a10

           Month    Concession         Type ATC1 ATC2  Scripts       Cost
1524  1991-07-01  Concessional  Co-payments    A  A10    89733  2092878.0
1525  1991-08-01  Concessional  Co-payments    A  A10    77101  1795733.0
1526  1991-09-01  Concessional  Co-payments    A  A10    76255  1777231.0
1527  1991-10-01  Concessional  Co-payments    A  A10    78681  1848507.0
1528  1991-11-01  Concessional  Co-payments    A  A10    70554  1686458.0
...          ...           ...          ...  ...  ...      ...        ...
52339 2008-02-01       General   Safety net    A  A10    10869   530709.0
52340 2008-03-01       General   Safety net    A  A10     1119    51773.0
52341 2008-04-01       General   Safety net    A  A10      721    36289.0
52342 2008-05-01       General   Safety net    A  A10     1947   101233.0
52343 2008-06-01       General   Safety net    A  A10     4331   193179.0

[816 rows x 7 columns]

In [16]:
a10 = (
    pbs.loc[pbs["ATC2"] == "A10"]
    .drop(columns=["ATC1", "ATC2"])
)
a10

           Month    Concession         Type  Scripts       Cost
1524  1991-07-01  Concessional  Co-payments    89733  2092878.0
1525  1991-08-01  Concessional  Co-payments    77101  1795733.0
1526  1991-09-01  Concessional  Co-payments    76255  1777231.0
1527  1991-10-01  Concessional  Co-payments    78681  1848507.0
1528  1991-11-01  Concessional  Co-payments    70554  1686458.0
...          ...           ...          ...      ...        ...
52339 2008-02-01       General   Safety net    10869   530709.0
52340 2008-03-01       General   Safety net     1119    51773.0
52341 2008-04-01       General   Safety net      721    36289.0
52342 2008-05-01       General   Safety net     1947   101233.0
52343 2008-06-01       General   Safety net     4331   193179.0

[816 rows x 5 columns]

In [17]:
total_cost_df = (
    pbs.loc[pbs["ATC2"] == "A10"]
    .drop(columns=["ATC1", "ATC2"])
    .groupby("Month", as_index=False)
    .agg({"Cost": "sum"})
    .rename(columns={"Cost": "TotalC"})
)
total_cost_df

         Month      TotalC
0   1991-07-01   3526591.0
1   1991-08-01   3180891.0
2   1991-09-01   3252221.0
3   1991-10-01   3611003.0
4   1991-11-01   3565869.0
..         ...         ...
199 2008-02-01  21654285.0
200 2008-03-01  18264945.0
201 2008-04-01  23107677.0
202 2008-05-01  22912510.0
203 2008-06-01  19431740.0

[204 rows x 2 columns]

In [18]:
total_cost_df = (
    pbs.loc[pbs["ATC2"] == "A10"]
    .drop(columns=["ATC1", "ATC2"])
    .groupby("Month", as_index=False)
    .agg({"Cost": "sum"})
    .assign(Cost=lambda x: (x["Cost"] / 1e6).round(2))
)
total_cost_df

         Month   Cost
0   1991-07-01   3.53
1   1991-08-01   3.18
2   1991-09-01   3.25
3   1991-10-01   3.61
4   1991-11-01   3.57
..         ...    ...
199 2008-02-01  21.65
200 2008-03-01  18.26
201 2008-04-01  23.11
202 2008-05-01  22.91
203 2008-06-01  19.43

[204 rows x 2 columns]

In [19]:
prison = (
    pd.read_csv("../data/prison_population.csv", parse_dates=["Date"])
    .rename(columns={"Date": "Quarter"})
    .sort_values(by=["State", "Gender", "Legal", "Indigenous"])
)
prison

        Quarter State  Gender      Legal Indigenous  Count
0    2005-03-01   ACT  Female   Remanded       ATSI      0
64   2005-06-01   ACT  Female   Remanded       ATSI      1
128  2005-09-01   ACT  Female   Remanded       ATSI      0
192  2005-12-01   ACT  Female   Remanded       ATSI      0
256  2006-03-01   ACT  Female   Remanded       ATSI      1
...         ...   ...     ...        ...        ...    ...
2815 2015-12-01    WA    Male  Sentenced   Non-ATSI   2503
2879 2016-03-01    WA    Male  Sentenced   Non-ATSI   2488
2943 2016-06-01    WA    Male  Sentenced   Non-ATSI   2539
3007 2016-09-01    WA    Male  Sentenced   Non-ATSI   2608
3071 2016-12-01    WA    Male  Sentenced   Non-ATSI   2625

[3072 rows x 6 columns]

In [20]:
total_cost_df.to_csv("../data/total_cost_df.csv", index=False)